changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat

  categories:
    - title: 💥 Breaking Changes
      labels:
        - breaking

    - title: 🐛 Bug Fixes
      labels:
        - bug

    - title: 🧹 Chores
        - chore

    - title: 🔗 Dependencies
      labels:
        - dependencies

    - title: 🔥 Deprecations and Removals
      labels:
        - deprecation

    - title: 📚 Documentation Improvements
      labels:
        - documentation

    - title: 🛠️ Improvements
      labels:
        - improvement

    - title: ✨ Features
      labels:
        - feature

    - title: ⚡️ Performance Improvements
      labels:
        - performance
        - "type: performance"

    - title: 🔒 Security Updates
      labels:
        - security
        - type:security

    - title: 🧪 Testing
      labels:
        - testing
        - type-testing

    - title: 🔁 Other Changes
      labels:
        - "*"
