changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat

  categories:
    - title: 🚀 Features
      labels:
        - enhancement
        - feature

    - title: 🐛 Bug Fixes
      labels:
        - bug
        - bugfix
        - fix

    - title: 🧰 Maintenance
        - chore

    - title: Other Changes
      labels:
        - "*"
