changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat

  categories:
    - title: 🛠 Breaking Changes
      labels:
        - breaking-change

    - title: 🎉 Features
      labels:
        - feature

    - title: 🚀 Enhancements
      labels:
        - enhancement

    - title: 🐛 Bug Fixes
      labels:
        - bug

    - title: 🧹 Chores
        - chore

    - title: 📦 Dependencies
      labels:
        - dependencies

    #- title: 📖 Documentation
    #  labels:
    #    - dependencies

    - title: 💡 Other Changes
      labels:
        - "*"
