inputs:
  cache-hit:
    description: ''
    required: true

  poetry-version:
    description: ''
    required: false
    default: ''

  poetry-home:
    description: ''
    required: false
    default: ''

  poetry-path:
    description: ''
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
  - name: Install Poetry
    if: inputs.cache-hit != 'true'
    shell: bash
    env:
      POETRY_VERSION: ${{ inputs.poetry-version }}
      POETRY_HOME: ${{ inputs.poetry-home }}
    env:
      curl -sSL https://install.python-poetry.org | python3 -

  - name: Add Poetry to the PATH environment variable
    if: inputs.poetry-path != ''
    shell: bash
    run: |
      echo "${{ inputs.poetry-path }}" >> $GITHUB_PATH
