name: caller

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-local:
    # if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: .github/python-version.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'poetry>=1.2'
          poetry self add 'poetry-dynamic-versioning[plugin]'
          poetry install --with dev --no-interaction
      - name: Lint with flake8
        run: |
          poetry run tox -e flake8

  Reuse:
    needs: lint-local
    permissions:
      contents: read
      pages: write
      id-token: write    
    uses: ./.github/workflows/callee.yml
