name: Debug7

on: workflow_dispatch

permissions:
  contents: read

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      matrix2: ${{ steps.set-matrix2.outputs.matrix2 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read JSON file
        id: set-matrix
        shell: bash
        run: |
          JSON=$(cat .github/workflows/test_matrix.json)
          echo 'matrix<<EOF' >> $GITHUB_OUTPUT
          echo "${JSON}" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main
        with:
          file: './.github/test_matrix.yml'

      - name: output
        id: set-matrix2
        shell: bash
        run: |
          echo 'matrix2<<EOF' >> $GITHUB_OUTPUT
          echo "${{ steps.yaml-data.outputs.data }}" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

  build:
    needs: matrix_prep
    strategy:
      fail-fast: false
      #matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}
      matrix: ${{ needs.matrix_prep.outputs.matrix2 }}

    runs-on: ${{ matrix.os }}
    name: ${{ format('build ({0}, {1})', matrix.os, matrix.python-version) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Poetry ${{ matrix.poetry-version }}
        id: setup-poetry
        uses: ./.github/actions/setup-poetry
        with:
          cache-path: ${{ matrix.poetry-cache-paths }}
          cache-key: temp-7-${{ format(matrix.poetry-cache-key-fmt, matrix.poetry-version, matrix.os, matrix.python-version) }}
          poetry-version: ${{ matrix.poetry-version }}
          poetry-home: ${{ matrix.poetry-home }}
          poetry-path: ${{ matrix.poetry-path }}

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
      - name: Set up Poetry dependencies
        id: setup-poetry-dependencies
        uses: ./.github/actions/setup-poetry-dependencies
        with:
          cache-path: .venv
          cache-key: temp-7-${{ format(matrix.venv-cache-key-fmt, matrix.os, matrix.python-version, hashFiles('**/poetry.lock')) }}
          python-version: ${{ matrix.python-version }}
          poetry-install-args: --no-interaction --no-root --with dev

      #- name: Install project
      #  run: poetry install --no-interaction --only-root

      - name: Test with pytest
        run: |
          poetry run tox -e py
