name: gh-cli

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: cmd
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        run: |
          gh api -X GET repos/{org}/{repo}/actions/caches/{CACHE_ID}
