name: gh-cli

on:
  workflow_dispatch:

jobs:
  debug:
    permissions:
      actions: write

    runs-on: ubuntu-latest
    steps:
      - name: Debug
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            for (const cache of caches.data.actions_caches) {
              console.log(cache);
            }
            const date1 = new Date('2022-04-16T06:55:31.820Z');
            console.log(date1);
    
      #- name: cmd
      #  shell: bash
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    OWNER: ${{ github.repository_owner }}
      #    REPO: ${{ github.event.repository.name }}          
      #  run: |
      #    #gh api -X GET repos/${OWNER}/${REPO}/actions/caches/{CACHE_ID}
      #    gh api -X GET repos/${OWNER}/${REPO}/actions/caches

###
#jobs:
#  clear-cache:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Clear cache
#        uses: actions/github-script@v6
#        with:
#          script: |
#            console.log("About to clear")
#            const caches = await github.rest.actions.getActionsCacheList({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#            })
#            for (const cache of caches.data.actions_caches) {
#              console.log(cache)
#              github.rest.actions.deleteActionsCacheById({
#                owner: context.repo.owner,
#                repo: context.repo.repo,
#                cache_id: cache.id,
#              })
#            }
#            console.log("Clear completed")
