name: Test ghs

on:
  issues:
    types: [opened]

jobs:
  initial_setting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        timeout-minutes: 5
        with:
          script: |
            // Add comment.
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
            // Get the current issue.
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            // Apply assignee if needed.
            if (github.event.issue.assignees.length == 0) {
              github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: `${{ github.actor }}`
              });
            }
            // Apply label if needed.
            if (issue.data.labels.length == 0) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['needs triage']
              });
            }
