name: Test ghs

on:
  issues:
    types: [opened]

jobs:
  add-comment:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        timeout-minutes: 5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            });

  apply-label:
    needs: [add-comment]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        timeout-minutes: 5
        with:
          script: |
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            if (issue.data.labels.length > 0) {
              return;
            }
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs triage']
            });

  assign-assignee:
    needs: [add-comment]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        timeout-minutes: 5
        with:
          script: |
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            if (issue.data.assignees.length > 0) {
              return;
            }
            let assignee;
            try {
              const ret = await github.rest.issues.checkUserCanBeAssigned({
                owner: context.repo.owner,
                repo: context.repo.repo,
                assignee: `${{ github.actor }}`
              });
              assignee = `${{ github.actor }}`;
            } catch (e) {
              assignee = `${{ github.repository_owner }}`;
            }
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: assignee
            });

  initial_setting:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        timeout-minutes: 5
        with:
          script: |
            let assignee;
            try {
              const ret = await github.rest.issues.checkUserCanBeAssigned({
                owner: context.repo.owner,
                repo: context.repo.repo,
                assignee: `${{ github.actor }}`
              });
              assignee = `${{ github.actor }}`
            } catch (e) {
              assignee = `${{ github.repository_owner }}`
            }
            console.log('assignee:', assignee)
    
      - uses: actions/github-script@v6
        timeout-minutes: 5
        with:
          script: |
            const ret1 = await github.rest.issues.checkUserCanBeAssigned({
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignee: `${{ github.repository_owner }}`
            });
            console.log(ret1)
            try {
              const ret2 = await github.rest.issues.checkUserCanBeAssigned({
                owner: context.repo.owner,
                repo: context.repo.repo,
                assignee: `${{ github.actor }}`
              });
              console.log(ret2)
            } catch(e) {
              console.log(typeof e)
              console.log(e instanceof Error)
              console.log(e.name)
              console.log(e.message)
            }
          
            // Add comment.
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            });
            // Get the current issue.
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            // Apply assignee if needed.
            if (issue.data.assignees.length == 0) {
              github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: `${{ github.repository_owner }}`
              });
            }
            // Apply label if needed.
            if (issue.data.labels.length == 0) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['needs triage']
              });
            }
