name: Lab3

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #python-version: ['3.7', '3.8']
        #os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: ['3.7', ]
        os: [windows-latest, ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Make cache paths
        id: make-cache-paths
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            PATH1='~\AppData\Local\pypoetry'
            PATH2='~\AppData\Roaming\pypoetry'
            PATH3='~\AppData\Roaming\Python\Scripts'
            echo 'CACHE_PATHS<<EOF' >> $GITHUB_ENV
            echo -e "${PATH1}\n${PATH2}\n${PATH3}" >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
          else
            PATH='~/.local'
            echo "CACHE_PATHS=${PATH}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.CACHE_PATHS }}
          key: lab3-poetry-${{ matrix.os }}-python-${{ matrix.python-version }}

      - name: Install Poetry for Linux/macOS
        if: runner.os != 'Windows' && steps.cached-poetry.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_HOME=/.local py -
        shell: bash

      # https://github.com/python-poetry/poetry/issues/6875#issuecomment-1315476316
      - name: Install Poetry for Windows
        if: runner.os == 'Windows' && steps.cached-poetry.outputs.cache-hit != 'true'
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -
        shell: pwsh

      - name: Add paths for macOS
        if: runner.os == 'macOS'
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
        shell: bash

      - name: Add paths for Windows
        if: runner.os == 'Windows'
        run: Add-Content $env:GITHUB_PATH "$env:APPDATA\pypoetry\venv\Scripts"
        shell: pwsh

      - name: Debug
        run: |
          poetry --version

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: lab3-venv-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root --with dev
      - name: Install project
        run: poetry install --no-interaction --only-root

      - name: Get the environment name for Tox
        id: vars
        run: |
          import os
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
              value = str(${{ matrix.python-version }}).replace('.', '')
              print(f'env=py{value}', file=fh)
        shell: python

      - name: Test with pytest
        run: |
          #poetry run tox -e py # This is not possible on Windows.
          poetry run tox -e ${{ steps.vars.outputs.env }}
