name: Lint

#on: [ push, pull_request ]
on: workflow_dispatch

permissions:
  contents: read

jobs:
  env_prep:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.set-env.outputs.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read JSON file
        id: set-env
        shell: bash
        run: |
          JSON=$(cat .github/workflows/env.json)
          echo 'env<<EOF' >> $GITHUB_OUTPUT
          echo "${JSON}" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

  build:
    needs: env_prep
    env: ${{ fromJson(needs.env_prep.outputs.env) }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - name: Set up Poetry
        id: setup-poetry
        uses: ./.github/actions/setup-poetry
        with:
          cache-path: ${{ env.poetry_cache_paths }}
          cache-key: temp-5-${{ format(env.poetry_cache_key_fmt, env.poetry_version, runner.os, steps.setup-python.outputs.python-version) }}
          poetry-version: ${{ env.poetry_version }}
          poetry-home: ${{ env.poetry_home }}
          poetry-path: ${{ env.poetry_path }}

      #- name: Load cached Poetry installation
      #  id: cached-poetry
      #  uses: actions/cache@v3
      #  with:
      #    path: ${{ env.poetry_cache_paths }}
      #    key: ${{ format(env.poetry_cache_key_fmt, env.poetry_version, runner.os, steps.setup-python.outputs.python-version) }}

      #- name: Install Poetry
      #  if: steps.cached-poetry.outputs.cache-hit != 'true'
      #  shell: bash
      #  env:
      #    POETRY_VERSION: ${{ env.poetry_version }}
      #    POETRY_HOME: ${{ env.poetry_home }}
      #  run: |
      #    curl -sSL https://install.python-poetry.org | python3 -

      #- name: Add Poetry to the PATH environment variable
      #  if: env.poetry_path != ''
      #  shell: bash
      #  run: |
      #    echo "${{ env.poetry_path }}" >> $GITHUB_PATH

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ format(env.venv_cache_key_fmt, runner.os, steps.setup-python.outputs.python-version, hashFiles('**/poetry.lock')) }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --only dev

      #- name: Install project
      #  run: poetry install --no-interaction --only-root

      - name: Lint with tox
        run: |
          poetry run tox -e black,isort,flake8,mypy -p all -q
