name: '🧰 Maint: Dump rate limit'

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Dump rate limit 
        uses: actions/github-script@v6
        with:
          script: |
            const rate_limit = await github.request('GET /rate_limit', {});
            core.notice(JSON.stringify(rate_limit, undefined, 2));

            const table = [];
            const header = Object.keys(rate_limit.data.rate).map(v => ({data: v, header: true}));
            header.push({data: 'date', header: true});
            header.unshift({data: 'resource', header: true});
            table.push(header);

            const current_date = new Date();

            for (let [key, value] of Object.entries(rate_limit.data.resources)) {
              const resource = Object.values(value).map(v => v.toString());
              //resource.push(new Date(value.reset * 1000).toString());
              const reset = new Date(value.reset);
              const time_left = Math.floor((reset - current_date) / 60000);
              resource.push(time_left.toString());
              
              resource.unshift(key);
              table.push(resource);
            }

            await core.summary
              .addHeading('rate_limit')
              .addRaw('Created at ' + new Date().toString())
              .addTable(table)
              .write()
