name: '🧰 Maint: Dump rate limit'

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Dump rate limit 
        uses: actions/github-script@v6
        with:
          script: |
            const rate_limit = await github.request('GET /rate_limit', {});
            core.notice(JSON.stringify(rate_limit.data.resources, undefined, 2));

      - name: Debug
        uses: actions/github-script@v6
        with:
          script: |
            const rate_limit = await github.request('GET /rate_limit', {});
            core.notice(rate_limit.data.resources.core);
            
            core.notice(rate_limit.data.resources.core instanceof Map);
            //core.notice(rate_limit.data.resources.core.values());
            
            let header = []
            for (key of Object.keys(rate_limit.data.rate)) {
              header.push({data: key, header: true});
            }
            core.notice(header);
            
            ///rate_limit.data.rate
            
           
            await core.summary
              .addHeading('Test')
              .addTable([
                header,
                Object.values(rate_limit.data.resources.core).map(v => v.toString()),
                ['1','2','3','4'],
              ])
              .write()
