name: [MAINT] Delete caches

on:
  workflow_dispatch:

jobs:
  debug:
    permissions:
      actions: write

    runs-on: ubuntu-latest
    steps:
      - name: Debug
        uses: actions/github-script@v6
        with:
          script: |
            const validity_days = 7;
            const current_date = new Date();
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            for (const cache of caches.data.actions_caches) {
              const expiry_date = new Date(cache.last_accessed_at);
              expiry_date.setDate(expiry_date.getDate() + validity_days)

              if (current_date > expiry_date) {
                console.log('expired', new Date(cache.last_accessed_at));
              } else {
                console.log('not expired', new Date(cache.last_accessed_at));
              }
            }

###
#jobs:
#  clear-cache:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Clear cache
#        uses: actions/github-script@v6
#        with:
#          script: |
#            console.log("About to clear")
#            const caches = await github.rest.actions.getActionsCacheList({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#            })
#            for (const cache of caches.data.actions_caches) {
#              console.log(cache)
#              github.rest.actions.deleteActionsCacheById({
#                owner: context.repo.owner,
#                repo: context.repo.repo,
#                cache_id: cache.id,
#              })
#            }
#            console.log("Clear completed")
