name: 🚧🧰 Maint - Delete workflow runs

on:
  workflow_dispatch:
    inputs:
      dry-run:
        required: false
        default: true
        type: boolean

jobs:
  main:
    permissions:
      actions: write

    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: actions/github-script@v6
        with:
          script: |
            const wfs = await github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            //console.debug(wfs);
            //console.debug(wfs.data.workflows[0].id);
            const workflow_id = 'maint_delete_wf_runs.yml';
            //const workflow_id = wfs.data.workflows[0].id;

            const wf_runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow_id,
            });
            console.debug(wf_runs.data.workflow_runs.length);
            console.debug(wf_runs.data.workflow_runs[0]);

            for (const wf_run of wf_runs.data.workflow_runs) {
              github.rest.actions.deleteWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: wf_run.id,
              });
            }
