name: 🚧🧰 Maint - Delete caches

on:
  workflow_dispatch:
    inputs:
      validity_days:
        description: 'Validity days'
        default: '7'
        type: choice
        options: ['0', '1', '2', '3', '4', '5', '6', '7']

      pattern:
        description: ''
        required: false
        default: ''
        type: string

jobs:
  main:
    permissions:
      actions: write

    runs-on: ubuntu-latest
    steps:
      - name: Debug
        uses: actions/github-script@v6
        with:
          script: |
            //let pattern = /^\d{3}-?\d{4}$/g;
            const re = /${{ inputs.pattern }}/
            const postcode = '121-4440';
            const result = re.test(postcode)
            console.debug(result)

      - name: Delete caches
        uses: actions/github-script@v6
        with:
          script: |
            const validity_days = parseInt(`${{ inputs.validity_days }}`, 10);
            const current_date = new Date();
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            let num_deleted_caches = 0;
            for (const cache of caches.data.actions_caches) {
              const expiry_date = new Date(cache.last_accessed_at);
              expiry_date.setDate(expiry_date.getDate() + validity_days)
              if (current_date.getTime() > expiry_date.getTime()) {
                github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                });
                num_deleted_caches++;
              }
            }
            console.info(`${num_deleted_caches}/${caches.data.actions_caches.length} caches have been deleted.`);
