name: 🚧🧰 Maint - Dump rate limit

on:
  workflow_dispatch:

jobs:
  main:
    #permissions:
    #  actions: read

    runs-on: ubuntu-latest
    steps:
      - name: Dump rate limit 
        uses: actions/github-script@v6
        with:
          script: |
            const rate_limit = await github.request('GET /rate_limit', {});
            console.info(rate_limit);
            //core.notice(rate_limit.data.resources.core);
            core.notice(JSON.stringify(rate_limit.data.resources));

      - name: Debug
        uses: actions/github-script@v6
        with:
          script: |
            core.notice('This is a message that will also emit an annotation');
            core.info('Output to the actions build log')
            core.error('This is a bad error, action may still succeed though.')
            core.warning('Something went wrong, but it\'s not bad enough to fail the build.')
