name: '🧰 Maint: Dump rate limit'

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Dump rate limit 
        uses: actions/github-script@v6
        with:
          script: |
            const rate_limit = await github.request('GET /rate_limit', {});
            core.notice(JSON.stringify(rate_limit.data.resources, undefined, 2));

      - name: Debug
        uses: actions/github-script@v6
        with:
          script: |
            const rate_limit = await github.request('GET /rate_limit', {});
            core.notice(rate_limit.data.resources.core);
            
            core.notice(rate_limit.data.resources.core instanceof Map);
            //core.notice(rate_limit.data.resources.core.values());
           
            await core.summary
              .addHeading('Test')
              .addTable([
                [{data: 'limit', header: true},
                 {data: 'used', header: true},
                 {data: 'remaining', header: true},
                 {data: 'reset', header: true}],
                Object.values(rate_limit.data.resources.core),
                ['1','2','3','4'],
              ])
              .write()
