name: '🧰 Maint: Dump rate limit'

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Dump rate limit 
        uses: actions/github-script@v6
        with:
          script: |
            const rate_limit = await github.request('GET /rate_limit', {});
            core.notice(JSON.stringify(rate_limit.data.resources, undefined, 2));

      - name: Debug
        uses: actions/github-script@v6
        with:
          script: |
            const rate_limit = await github.request('GET /rate_limit', {});

            let table = [];
            table.push(Object.keys(rate_limit.data.rate).map(v => ({data: v, header: true})));
            for (let value of Object.values(rate_limit.data.resources)) {
              table.push(Object.values(value).map(v => v.toString()));
            }

            await core.summary
              .addHeading('Test')
              .addTable(table)
              .write()
