name: 🚧🧰 Maint - Delete workflow runs

on:
  workflow_dispatch:
    inputs:
      validity-days:
        description: 'Validity days'
        default: '7'
        type: choice
        options: ['0', '1', '2', '3', '4', '5', '6', '7']

      name-pattern:
        description: 'Regular expression to match workflow name'
        required: false
        default: ''
        type: string

      dry-run:
        required: false
        default: true
        type: boolean

jobs:
  main:
    permissions:
      actions: write

    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: actions/github-script@v6
        with:
          script: |
            const validity_days = parseInt('${{ inputs.validity-days }}', 10);
            const re = new RegExp('${{ inputs.name-pattern }}');

            const wfs = await github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            for (const wf of wfs.data.workflows) {
              //const has_matched = re.test(cache.key);
              //console.debug(wf)
              console.debug(path.basename(wf.path))
            }
            
            //console.debug(wfs);
            //console.debug(wfs.data.workflows[0].id);
            const workflow_id = 'maint_delete_wf_runs.yml';
            //const workflow_id = wfs.data.workflows[0].id;

            const wf_runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow_id,
            });
            console.debug(wf_runs.data.workflow_runs.length);
            console.debug(wf_runs.data.workflow_runs[0]);

            for (const wf_run of wf_runs.data.workflow_runs) {
              console.debug(wf_run.status == 'completed');
              //updated_at
            }
