name: 🧰 Maint - Delete caches

on:
  workflow_dispatch:
    inputs:
      dry-run:
        required: false
        default: true
        type: boolean

      validity-days:
        description: 'Validity days'
        default: '7'
        type: choice
        options: ['0', '1', '2', '3', '4', '5', '6', '7']

      key-pattern:
        description: 'Regular expression to match cache key'
        required: false
        default: ''
        type: string

jobs:
  main:
    permissions:
      actions: write

    runs-on: ubuntu-latest
    steps:
      - name: Delete caches
        uses: actions/github-script@v6
        with:
          script: |
            const validity_days = parseInt(`${{ inputs.validity-days }}`, 10);
            const re = new RegExp('${{ inputs.key-pattern }}');
            const current_date = new Date();
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            let num_deleted_caches = 0;
            for (const cache of caches.data.actions_caches) {
              const expiry_date = new Date(cache.last_accessed_at);
              expiry_date.setDate(expiry_date.getDate() + validity_days);
              const has_expired = current_date.getTime() > expiry_date.getTime();
              const has_matched = re.test(cache.key);
              if (current_date.getTime() > expiry_date.getTime()) {
                github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                });
                num_deleted_caches++;
              }
            }
            console.info(`${num_deleted_caches}/${caches.data.actions_caches.length} caches have been deleted.`);
