# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry poetry-dynamic-versioning
    - name: Build
      run: |
        poetry build
    - name: publish
      env:
        TESTPYPI_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
        TESTPYPI_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
        TESTPYPI_API_TOKEN: ${{ secrets.TESTPYPI_API_TOKEN }}
        TEST_MSG: ${{ secrets.TEST_MSG }}
        PUB_MSG: 'Hello, world!!!'
      run: |
        echo "The GitHub Action Secret will be masked:  "
        echo ${{ secrets.TEST_MSG }}
        echo env.TEST_MSG
        echo $PUB_MSG
        echo "The GitHub Action Secret will be masked:  "
        #poetry config repositories.test-pypi https://test.pypi.org/legacy/
        #poetry config pypi-token.test-pypi ${{ secrets.TESTPYPI_API_TOKEN }}
        #poetry publish -r test-pypi
        #poetry publish -r test-pypi --username env.TESTPYPI_USERNAME --password env.TESTPYPI_PASSWORD
