name: '🚧🎁 Release'

on:
  push:
  workflow_dispatch:
  #release:
  #  types: [published]

jobs:
  config-prep:
    runs-on: ubuntu-latest
    outputs:
      enable-docs: ${{ steps.read-file.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read YAML file
        id: read-file
        uses: ./.github/actions/read-yaml
        with:
          path: .github/settings/release_config.yml
          filter: '.default.enable-docs'

      - name: Debug
        shell: bash
        run: |
          echo "${{ github.event_name }}"

  publish-package:
    uses: ./.github/workflows/testpypi.yml
    with:
      dry-run: ${{ github.event_name == 'workflow_dispatch' }}
    secrets: inherit

  publish-docs:
    needs: [config-prep, publish-package]
    if: needs.config-prep.outputs.enable-docs == 'true'
    uses: ./.github/workflows/docs.yml
