name: Test

#on: [ push, pull_request ]
on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8']
        #os: [ubuntu-20.04, macos-latest, windows-latest]
        os: [ubuntu-20.04, ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.in-project true
    - name: Install dependencies
      run: poetry install --no-interaction --only dev
    - name: Install project
      run: poetry install --no-interaction --only-root
    - name: Test with pytest
      run: poetry run tox -e py
