name: Workflow Run Trigger

on:
  workflow_run:
    workflows:
      - Lint
    types:
      - completed

jobs:
  main:
    runs-on: ubuntu-latest
    # 呼び元のworkflowの結果がsuccessであればmain jobを実行
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Debug
      shell: bash
      run: |
        echo ${{ github.event }}
        echo ${{ github.event.workflow_run }}
